# Generated by Django 4.2.26 on 2025-11-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bus_country', models.CharField(max_length=50)),
                ('bus_state', models.CharField(max_length=50)),
                ('bus_street', models.CharField(max_length=50)),
                ('cac_reg_no', models.CharField(max_length=10)),
                ('nin', models.CharField(default='11111111111', max_length=11)),
                ('phone_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=70)),
                ('cour_photo', models.CharField(max_length=200)),
                ('cour_policy', models.BooleanField()),
                ('password', models.CharField(max_length=200)),
                ('appr_officer', models.CharField(max_length=100)),
                ('appr_date', models.CharField(default='2022-04-23T12:25:32.355Z', max_length=100)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourierBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=70)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], max_length=20)),
                ('account_name', models.CharField(max_length=70)),
                ('courier_email', models.EmailField(max_length=70)),
                ('account_no', models.CharField(max_length=15)),
                ('added_at', models.CharField(max_length=50)),
                ('updated_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.CharField(max_length=70)),
                ('complaint_subject', models.CharField(max_length=125)),
                ('courier_involved', models.CharField(default='Anonymous', max_length=125)),
                ('complaint_detail', models.TextField(max_length=1000)),
                ('is_resolved', models.BooleanField()),
                ('is_satisfied', models.BooleanField()),
                ('created_at', models.CharField(default='dummy_date', max_length=50)),
                ('updated_at', models.CharField(default='dummy_date', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=80)),
                ('photo', models.ImageField(upload_to='staff-photo/')),
                ('password', models.CharField(max_length=100)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TempCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bus_country', models.CharField(max_length=50)),
                ('bus_state', models.CharField(max_length=50)),
                ('bus_street', models.CharField(max_length=50)),
                ('cac_reg_no', models.CharField(max_length=10)),
                ('nin', models.CharField(default='11111111111', max_length=11)),
                ('phone_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=70)),
                ('cour_photo', models.ImageField(upload_to='courier_images/')),
                ('cour_policy', models.BooleanField()),
                ('password', models.CharField(max_length=200)),
                ('reg_date', models.CharField(default='2022-04-23T12:25:32.355Z', max_length=100)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TempVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bus_country', models.CharField(max_length=50)),
                ('bus_state', models.CharField(max_length=50)),
                ('bus_street', models.CharField(max_length=50)),
                ('bus_category', models.CharField(blank=True, choices=[('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Chemicals', 'Chemicals'), ('Educative_Materials', 'Educative Materials'), ('Furniture', 'Furniture'), ('Kitchen_Utensils', 'Kitchen Utensils'), ('Plastics', 'Plastics'), ('Spare_Parts', 'Spare Parts'), ('General_Merchandise', 'General Merchandise')], max_length=25)),
                ('cac_reg_no', models.CharField(max_length=10)),
                ('nin', models.CharField(default='11111111111', max_length=11)),
                ('phone_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=70)),
                ('vend_photo', models.ImageField(upload_to='vendor_images/')),
                ('ven_policy', models.BooleanField()),
                ('password', models.CharField(max_length=200)),
                ('reg_date', models.CharField(default='2022-04-23T12:25:32.355Z', max_length=100)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bus_country', models.CharField(max_length=50)),
                ('bus_state', models.CharField(max_length=50)),
                ('bus_street', models.CharField(max_length=50)),
                ('bus_category', models.CharField(max_length=25)),
                ('cac_reg_no', models.CharField(max_length=10)),
                ('nin', models.CharField(default='11111111111', max_length=11)),
                ('phone_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=70)),
                ('vend_photo', models.CharField(max_length=200)),
                ('ven_policy', models.BooleanField()),
                ('password', models.CharField(max_length=200)),
                ('appr_officer', models.CharField(max_length=100)),
                ('appr_date', models.CharField(default='2022-04-23T12:25:32.355Z', max_length=100)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VendorBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=70)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], max_length=20)),
                ('account_name', models.CharField(max_length=70)),
                ('vendor_email', models.EmailField(max_length=70)),
                ('account_no', models.CharField(max_length=15)),
                ('added_at', models.CharField(max_length=50)),
                ('updated_at', models.CharField(max_length=50)),
            ],
        ),
    ]
