# Generated by Django 3.2.9 on 2022-04-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0002_tempvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempvendor',
            name='bus_category',
            field=models.CharField(blank=True, choices=[('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Chemicals', 'Chemicals'), ('Educative_Materials', 'Educative Materials'), ('Furniture', 'Furniture'), ('Kitchen_Utensils', 'Kitchen Utensils'), ('Plastics', 'Plastics'), ('Spare_Parts', 'Spare Parts'), ('General_Merchandise', 'General Merchandise')], max_length=25),
        ),
    ]
