# Generated by Django 3.2.9 on 2022-04-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0003_tempvendor_bus_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempvendor',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
