# Generated by Django 3.2.9 on 2022-04-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0004_alter_tempvendor_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bus_country', models.CharField(max_length=50)),
                ('bus_state', models.CharField(max_length=50)),
                ('bus_street', models.CharField(max_length=50)),
                ('cac_reg_no', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
