# Generated by Django 3.2.9 on 2022-04-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0005_tempcourier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempvendor',
            name='vend_photo',
            field=models.FileField(default='avatar', upload_to=''),
            preserve_default=False,
        ),
    ]
