# Generated by Django 3.2.9 on 2022-04-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0007_tempvendor_ven_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempvendor',
            name='vend_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
