# Generated by Django 3.2.9 on 2022-04-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0008_alter_tempvendor_vend_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempvendor',
            name='vend_photo',
            field=models.ImageField(upload_to='vendor_images/'),
        ),
    ]
