# Generated by Django 3.2.9 on 2022-04-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0009_alter_tempvendor_vend_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcourier',
            name='cour_photo',
            field=models.ImageField(default='avatar', upload_to='courier_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempcourier',
            name='cour_policy',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
