# Generated by Django 3.2.9 on 2022-04-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0010_auto_20220420_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default='avatar', upload_to='staff-photo/'),
            preserve_default=False,
        ),
    ]
