# Generated by Django 3.2.9 on 2022-04-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0012_auto_20220420_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bus_country', models.CharField(max_length=50)),
                ('bus_state', models.CharField(max_length=50)),
                ('bus_street', models.CharField(max_length=50)),
                ('bus_category', models.CharField(max_length=25)),
                ('cac_reg_no', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=70)),
                ('vend_photo', models.ImageField(upload_to='appr_vendor_images/')),
                ('ven_policy', models.BooleanField()),
                ('password', models.CharField(max_length=200)),
                ('appr_officer', models.CharField(max_length=100)),
            ],
        ),
    ]
