# Generated by Django 3.2.9 on 2022-04-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0013_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vend_photo',
            field=models.URLField(),
        ),
    ]
