# Generated by Django 3.2.9 on 2022-04-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0014_alter_vendor_vend_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vend_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
