# Generated by Django 3.2.9 on 2022-04-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0017_alter_vendor_vend_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='appr_date',
            field=models.CharField(default='2022-04-23T12:25:32.355Z', max_length=100),
        ),
    ]
