# Generated by Django 3.2.9 on 2022-04-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0018_vendor_appr_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bus_country', models.CharField(max_length=50)),
                ('bus_state', models.CharField(max_length=50)),
                ('bus_street', models.CharField(max_length=50)),
                ('cac_reg_no', models.CharField(max_length=10)),
                ('nin', models.CharField(default='11111111111', max_length=11)),
                ('phone_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=70)),
                ('cour_photo', models.CharField(max_length=200)),
                ('cour_policy', models.BooleanField()),
                ('password', models.CharField(max_length=200)),
                ('appr_officer', models.CharField(max_length=100)),
                ('appr_date', models.CharField(default='2022-04-23T12:25:32.355Z', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tempcourier',
            name='nin',
            field=models.CharField(default='11111111111', max_length=11),
        ),
        migrations.AddField(
            model_name='tempcourier',
            name='reg_date',
            field=models.CharField(default='2022-04-23T12:25:32.355Z', max_length=100),
        ),
        migrations.AddField(
            model_name='tempvendor',
            name='nin',
            field=models.CharField(default='11111111111', max_length=11),
        ),
        migrations.AddField(
            model_name='tempvendor',
            name='reg_date',
            field=models.CharField(default='2022-04-23T12:25:32.355Z', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='nin',
            field=models.CharField(default='11111111111', max_length=11),
        ),
    ]
