# Generated by Django 3.2.9 on 2022-04-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0019_auto_20220425_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempcourier',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempvendor',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
