# Generated by Django 3.2.9 on 2022-05-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0020_auto_20220430_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
