# Generated by Django 3.2.9 on 2022-05-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0021_auto_20220503_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=70)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], max_length=20)),
                ('account_name', models.CharField(max_length=70)),
                ('account_no', models.CharField(max_length=15)),
                ('add_at', models.CharField(max_length=50)),
                ('updated_at', models.CharField(max_length=50)),
            ],
        ),
    ]
