# Generated by Django 3.2.9 on 2022-05-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0022_vendorbankdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbankdetail',
            name='vendor_email',
            field=models.EmailField(default='example@gmail.com', max_length=70),
            preserve_default=False,
        ),
    ]
