# Generated by Django 3.2.9 on 2022-05-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0023_vendorbankdetail_vendor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorbankdetail',
            old_name='add_at',
            new_name='added_at',
        ),
    ]
