# Generated by Django 3.2.9 on 2022-07-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0024_rename_add_at_vendorbankdetail_added_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=70)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], max_length=20)),
                ('account_name', models.CharField(max_length=70)),
                ('vendor_email', models.EmailField(max_length=70)),
                ('account_no', models.CharField(max_length=15)),
                ('added_at', models.CharField(max_length=50)),
                ('updated_at', models.CharField(max_length=50)),
            ],
        ),
    ]
