# Generated by Django 3.2.9 on 2022-07-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0025_courierbankdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courierbankdetail',
            old_name='vendor_email',
            new_name='courier_email',
        ),
    ]
