# Generated by Django 3.2.9 on 2022-11-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0027_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.CharField(max_length=70)),
                ('complaint_subject', models.CharField(max_length=125)),
                ('complaint_detail', models.TextField(max_length=1000)),
                ('is_resolved', models.BooleanField()),
                ('is_satisfied', models.BooleanField()),
            ],
        ),
    ]
