# Generated by Django 3.2.9 on 2022-11-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0028_customercomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='courier_involved',
            field=models.CharField(default='Anonymous', max_length=125),
        ),
    ]
