# Generated by Django 3.2.9 on 2022-11-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_backends', '0029_customercomplaint_courier_involved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='created_at',
            field=models.CharField(default='dummy_date', max_length=50),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='updated_at',
            field=models.CharField(default='dummy_date', max_length=50),
        ),
    ]
