# Generated by Django 3.2.9 on 2022-05-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('Card', 'Card'), ('Offline', 'Offline'), ('Bank', 'Bank')], max_length=25)),
                ('provider', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=15)),
                ('expiry', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('payment_id', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.CharField(max_length=100)),
                ('updated_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.CharField(max_length=100)),
                ('updated_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('provider', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('"Insufficient', '"Insufficient'), ('Fund"', 'Fund"'), ('Failed', 'Failed')], max_length=50)),
                ('created_at', models.CharField(max_length=100)),
                ('updated_at', models.CharField(max_length=100)),
            ],
        ),
    ]
