# Generated by Django 4.2.26 on 2025-11-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('is_customer', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('Card', 'Card'), ('Offline', 'Offline'), ('Bank', 'Bank')], max_length=25)),
                ('provider', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=15)),
                ('expiry', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('total_items', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('shipping_method', models.CharField(choices=[('Pick_up', 'Pick Up'), ('Delivery', 'Delivery')], default='Pick up', max_length=25)),
                ('shipping_fee', models.IntegerField(default=0)),
                ('zip_code', models.CharField(default='8000000', max_length=30)),
                ('payment_id', models.IntegerField(default=0)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_dispatched', models.BooleanField(default=False)),
                ('created_at', models.CharField(max_length=100)),
                ('updated_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('is_customer', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.CharField(max_length=100)),
                ('updated_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('is_customer', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
                ('shipping_fee', models.IntegerField(default=0)),
                ('grand_total_amount', models.IntegerField(default=0)),
                ('provider', models.CharField(choices=[('Master_Card', 'Master Card'), ('Verve_Card', 'Verve Card'), ('Visa_Card', 'Visa Card')], max_length=50)),
                ('payment_type', models.CharField(choices=[('Card_Payment', 'Card Payment'), ('Bank_Transfer', 'Bank Transfer'), ('Bank_Transfer_On_Delivery', 'Bank Transfer On Delivery')], max_length=25)),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Insufficient_Fund', 'Insufficient Fund'), ('Failed', 'Failed'), ('Partial', 'Partial')], max_length=50)),
                ('reference', models.CharField(default='xxxxxxxx', max_length=25)),
                ('created_at', models.CharField(max_length=100)),
                ('updated_at', models.CharField(max_length=100)),
            ],
        ),
    ]
