# Generated by Django 3.2.9 on 2022-05-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='status',
            field=models.CharField(choices=[('Successful', 'Successful'), ('Insufficient_Fund', 'Insufficient Fund'), ('Failed', 'Failed')], max_length=50),
        ),
    ]
