# Generated by Django 3.2.9 on 2022-05-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0002_alter_paymentdetail_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='total',
            new_name='total_items',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
