# Generated by Django 3.2.9 on 2022-05-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0003_auto_20220528_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='shipping_method',
            field=models.CharField(choices=[('Pick_up', 'Pick Up'), ('Delivery', 'Delivery')], default='Pick up', max_length=25),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='zip_code',
            field=models.CharField(default='8000000', max_length=30),
        ),
    ]
