# Generated by Django 3.2.9 on 2022-05-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0004_auto_20220528_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
