# Generated by Django 3.2.9 on 2022-05-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0005_auto_20220528_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='customer_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='payment_type',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash'), ('Bank', 'Bank')], default='Card', max_length=25),
            preserve_default=False,
        ),
    ]
