# Generated by Django 3.2.9 on 2022-05-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0007_alter_orderdetail_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='payment_id',
            field=models.IntegerField(default=0),
        ),
    ]
