# Generated by Django 3.2.9 on 2022-05-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0008_alter_orderdetail_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='provider',
            field=models.CharField(choices=[('Master_Card', 'Master Card'), ('Verve_Card', 'Verve Card'), ('Visa_Card', 'Visa Card')], max_length=50),
        ),
    ]
