# Generated by Django 3.2.9 on 2022-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0009_alter_paymentdetail_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='shipping_fee',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
