# Generated by Django 3.2.9 on 2022-06-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0010_orderdetail_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='grand_total_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='shipping_fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
