# Generated by Django 3.2.9 on 2022-06-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0011_auto_20220602_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_type',
            field=models.CharField(choices=[('Card_Payment', 'Card Payment'), ('Bank_Transfer', 'Bank Transfer'), ('Bank_Transfer_On_Delivery', 'Bank Transfer On Delivery')], max_length=25),
        ),
    ]
