# Generated by Django 3.2.9 on 2022-06-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0012_alter_paymentdetail_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='status',
            field=models.CharField(choices=[('Successful', 'Successful'), ('Insufficient_Fund', 'Insufficient Fund'), ('Failed', 'Failed'), ('Partial', 'Partial')], max_length=50),
        ),
    ]
