# Generated by Django 3.2.9 on 2022-06-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0013_alter_paymentdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='shipping_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='grand_total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='shipping_fee',
            field=models.IntegerField(default=0),
        ),
    ]
