# Generated by Django 3.2.9 on 2022-06-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0014_auto_20220603_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='trans_ref',
            field=models.CharField(default='xxxxxxxx', max_length=25),
        ),
    ]
