# Generated by Django 3.2.9 on 2022-06-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0015_paymentdetail_trans_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetail',
            old_name='trans_ref',
            new_name='reference',
        ),
    ]
