# Generated by Django 3.2.9 on 2022-06-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0016_rename_trans_ref_paymentdetail_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_dipatched',
            field=models.BooleanField(default=False),
        ),
    ]
