# Generated by Django 3.2.9 on 2022-06-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_order', '0017_orderdetail_is_dipatched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='is_dipatched',
            new_name='is_dispatched',
        ),
    ]
