# Generated by Django 3.2.9 on 2022-05-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_customer', '0003_cartdetail_cartsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default='No. 1 Happy Crescent', max_length=50),
            preserve_default=False,
        ),
    ]
