# Generated by Django 3.2.9 on 2022-05-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_customer', '0004_customer_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=70)),
                ('reg_date', models.CharField(max_length=100)),
            ],
        ),
    ]
