# Generated by Django 3.2.9 on 2022-05-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_customer', '0005_anonymouscustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsession',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
