# Generated by Django 3.2.9 on 2022-05-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_customer', '0006_cartsession_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
