# Generated by Django 3.2.9 on 2022-05-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_customer', '0007_cartdetail_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsession',
            name='shipping_method',
            field=models.CharField(choices=[('Pick', 'Pick'), ('up', 'Up')], default='Delivery', max_length=25),
        ),
        migrations.AddField(
            model_name='cartsession',
            name='zip_code',
            field=models.CharField(default='8000000', max_length=30),
        ),
    ]
