# Generated by Django 3.2.9 on 2022-05-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_customer', '0008_auto_20220522_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartsession',
            name='shipping_method',
            field=models.CharField(choices=[('Pick', 'Pick'), ('up', 'Up')], default='Pick up', max_length=25),
        ),
    ]
