# Generated by Django 3.2.9 on 2022-05-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_customer', '0009_alter_cartsession_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartsession',
            name='shipping_method',
            field=models.CharField(choices=[('Pick_up', 'Pick Up'), ('Delivery', 'Delivery')], default='Pick up', max_length=25),
        ),
    ]
