# Generated by Django 3.2.9 on 2022-05-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_customer', '0010_alter_cartsession_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsession',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
