# Generated by Django 3.2.9 on 2022-05-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempproduct',
            name='img_base',
            field=models.CharField(default='avatar.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
