# Generated by Django 3.2.9 on 2022-05-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_product', '0002_tempproduct_img_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=80)),
                ('vendor_phone', models.CharField(max_length=14)),
                ('vendor_email', models.EmailField(max_length=70)),
                ('vend_photo', models.CharField(max_length=200)),
                ('prod_cat', models.CharField(max_length=25)),
                ('prod_name', models.CharField(max_length=25)),
                ('prod_model', models.CharField(max_length=40)),
                ('prod_photo', models.ImageField(upload_to='product_images/')),
                ('prod_price', models.IntegerField()),
                ('prod_qty', models.IntegerField()),
                ('prod_disc', models.IntegerField()),
                ('prod_desc', models.TextField(max_length=500)),
                ('img_base', models.CharField(max_length=200)),
                ('appr_officer', models.CharField(max_length=80)),
                ('appr_date', models.CharField(default='2022-04-23T12:25:32.355Z', max_length=100)),
            ],
        ),
    ]
