# Generated by Django 3.2.9 on 2022-05-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_product', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_photo',
            field=models.CharField(max_length=200),
        ),
    ]
