# Generated by Django 3.2.9 on 2022-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_product', '0004_alter_product_prod_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.CharField(default='2022-04-23T12:25:32.355Z', max_length=100),
        ),
    ]
