# Generated by Django 3.2.9 on 2022-06-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=25)),
                ('customer_id', models.CharField(max_length=25)),
                ('customer_name', models.CharField(max_length=75)),
                ('address', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=75)),
                ('phone_no', models.CharField(max_length=14)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('shipping_method', models.CharField(max_length=25)),
                ('total_items', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('zip_code', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=25)),
                ('product_id', models.CharField(max_length=25)),
                ('product_name', models.CharField(max_length=75)),
                ('prod_photo', models.CharField(max_length=200)),
                ('prod_model', models.CharField(max_length=75)),
                ('prod_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('vendor_email', models.CharField(max_length=75)),
                ('vendor_phone', models.CharField(max_length=14)),
                ('vendor_name', models.CharField(max_length=75)),
                ('vendor_address', models.CharField(max_length=120)),
            ],
        ),
    ]
