# Generated by Django 3.2.9 on 2022-06-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchdetail',
            name='created_at',
            field=models.CharField(default='2022-04-23T12:25:32.355Z', max_length=100),
        ),
        migrations.AddField(
            model_name='dispatchdetail',
            name='updated_at',
            field=models.CharField(default='2022-04-23T12:25:32.355Z', max_length=100),
        ),
        migrations.AddField(
            model_name='dispatchedproduct',
            name='created_at',
            field=models.CharField(default='2022-04-23T12:25:32.355Z', max_length=100),
        ),
        migrations.AddField(
            model_name='dispatchedproduct',
            name='updated_at',
            field=models.CharField(default='2022-04-23T12:25:32.355Z', max_length=100),
        ),
    ]
