# Generated by Django 3.2.9 on 2022-07-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_dispatch', '0002_auto_20220627_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchdetail',
            name='courier_email',
            field=models.CharField(default='000', max_length=25),
        ),
        migrations.AddField(
            model_name='dispatchdetail',
            name='courier_id',
            field=models.CharField(default='000', max_length=25),
        ),
        migrations.AddField(
            model_name='dispatchdetail',
            name='courier_name',
            field=models.CharField(default='000', max_length=25),
        ),
        migrations.AddField(
            model_name='dispatchdetail',
            name='courier_phone',
            field=models.CharField(default='000', max_length=25),
        ),
        migrations.AddField(
            model_name='dispatchdetail',
            name='handled_dispatch',
            field=models.BooleanField(default=False),
        ),
    ]
