# Generated by Django 3.2.9 on 2022-07-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_dispatch', '0003_auto_20220709_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchedproduct',
            name='supply_ready',
            field=models.BooleanField(default=False),
        ),
    ]
