# Generated by Django 3.2.9 on 2022-07-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_dispatch', '0004_dispatchedproduct_supply_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchedproduct',
            name='supply_received',
            field=models.BooleanField(default=False),
        ),
    ]
