# Generated by Django 3.2.9 on 2022-07-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_dispatch', '0005_dispatchedproduct_supply_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchedproduct',
            old_name='supply_ready',
            new_name='is_supply_ready',
        ),
        migrations.RenameField(
            model_name='dispatchedproduct',
            old_name='supply_received',
            new_name='is_supply_received',
        ),
    ]
