# Generated by Django 3.2.9 on 2022-07-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_dispatch', '0006_auto_20220721_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchedproduct',
            name='is_supply_ready',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dispatchedproduct',
            name='is_supply_received',
            field=models.BooleanField(),
        ),
    ]
