# Generated by Django 3.2.9 on 2022-07-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_dispatch', '0007_auto_20220721_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchedproduct',
            name='is_supply_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dispatchedproduct',
            name='is_supply_received',
            field=models.BooleanField(default=False),
        ),
    ]
