# Generated by Django 4.2.26 on 2025-11-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='WebMaster@parcel_app.com', max_length=100)),
                ('recipient', models.TextField(max_length=2000)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=4000)),
                ('sent_at', models.CharField(default='2025-11-17 00:34:44.084762', max_length=100)),
            ],
        ),
    ]
