# Generated by Django 3.2.9 on 2022-08-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.TextField(max_length=2000)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=4000)),
                ('sent_at', models.CharField(default='2022-08-10 23:11:49.775736', max_length=100)),
            ],
        ),
    ]
