# Generated by Django 3.2.9 on 2022-08-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessage',
            name='sender',
            field=models.CharField(default='WebMaster@parcel_app.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='sentmessage',
            name='sent_at',
            field=models.CharField(default='2022-08-11 00:37:00.207543', max_length=100),
        ),
    ]
