# Generated by Django 3.2.9 on 2022-11-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_message', '0002_auto_20220811_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmessage',
            name='sent_at',
            field=models.CharField(default='2022-11-10 16:47:19.509929', max_length=100),
        ),
    ]
