# Generated by Django 3.2.9 on 2022-11-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_message', '0003_alter_sentmessage_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmessage',
            name='sent_at',
            field=models.CharField(default='2022-11-10 16:53:57.364054', max_length=100),
        ),
    ]
