# Generated by Django 3.2.9 on 2022-11-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_message', '0004_alter_sentmessage_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmessage',
            name='sent_at',
            field=models.CharField(default='2022-11-11 14:31:02.570421', max_length=100),
        ),
    ]
